### PR TITLE
aii-opennebula: handle warnings and minor fixes

### LINKED ISSUE #87: aii-opennebula: Split ONE functions in two to remove/create something
Split all ONE AII functions in two (to remove and create resources)

### LINKED ISSUE #88: aii-opennebula: Use TextRender

### LINKED ISSUE #91: aii-opennebula: Fix false error log "TIMEOUT! Image status: 1 is not ready yet..."
AII reports an timeout error 
[ERROR] TIMEOUT! Image status: 1 is not ready yet...
but the image is generated correctly.

### LINKED ISSUE #92: aii-opennebula: handle uninitialzed warnings
when doing a `aii-shellfe --remove` on a node that is not yet installed, the aii opennebula hook returns some unitialized warnings, that should be captured to give a cleaner error message

```
...
[INFO] Checking ONE image: master1.shuppet.os_vda
[ERROR] Removing these VM images: master1.shuppet.os_vda
[INFO] Testing ONE vnet network AR: altaria.os
Use of uninitialized value $arid in concatenation (.) or string at /usr/lib/perl/AII/opennebula.pm line 289.
[INFO] QUATTOR flag not found within AR, id: 
[ERROR] Quattor flag not found within AR. ONE AII is not allowed to remove this AR.
[INFO] Testing ONE vnet network AR: altaria.vsc
Use of uninitialized value $arid in concatenation (.) or string at /usr/lib/perl/AII/opennebula.pm line 289.
[INFO] QUATTOR flag not found within AR, id: 
[ERROR] Quattor flag not found within AR. ONE AII is not allowed to remove this AR.
[INFO] 1 to remove
...
```

### LINKED ISSUE #94: aii-opennebula: wait for images are removed
in the remove phase, and when the aii can remove the image, we should wait until the image is actually removed before proceeding.

### PR DESCRIPTION
**Pull request by alvarosimon**
rebase from another PR: https://github.com/stdweird/aii/pull/3

 * Fix #87 issue. Split ONE functions in two to remove/create something
 * Fix #91 issue. TIMEOUT error message
 * Fix #92 issue. Unhandled remove warnings
 * Fix #94 issue. Wait for images are removed
 * Fix #88 issue. Use TextRender 

It requires aii_*.tt config templates

### CODE REVIEW

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 1]
```diff
@@ -241,43 +292,70 @@ sub remove_and_create_vn_ars
...
-                } else {
-                    $main::this_app->error("Unable to create new AR within vnet: $vnet");
-                }
+                $self->create_vn_ars($one, $vnet, $ardata, $t);
             }
        }
     }
 }
 
+# Create VN AR leases
```
Comment (jrha) [inline aii-opennebula/src/main/perl/opennebula.pm]: What is a VN AR? It might be a good idea to explain?

File: aii-opennebula/src/test/perl/rpcdata.pm [hunk 2]
```diff
@@ -290,7 +290,7 @@ EOF
...
+<IMAGE_POOL><IMAGE><ID>43</ID><UID>0</UID><GID>0</GID><UNAME>oneadmin</UNAME><GNAME>oneadmin</GNAME><NAME>node630.cubone.os_vda</NAME><PERMISSIONS><OWNER_U>1</OWNER_U><OWNER_M>1</OWNER_M><OWNER_A>0</OWNER_A><GROUP_U>0</GROUP_U><GROUP_M>0</GROUP_M><GROUP_A>0</GROUP_A><OTHER_U>0</OTHER_U><OTHER_M>0</OTHER_M><OTHER_A>0</OTHER_A></PERMISSIONS><TYPE>0</TYPE><DISK_TYPE>3</DISK_TYPE><PERSISTENT>0</PERSISTENT><REGTIME>1410854276</REGTIME><SOURCE><![CDATA[one/one-43]]></SOURCE><PATH><![CDATA[http://marketplace.c12g.com/appliance/4fc76a938fb81d3517000003/download/0]]></PATH><FSTYPE><![CDATA[]]></FSTYPE><SIZE>40</SIZE><STATE>1</STATE><RUNNING_VMS>1</RUNNING_VMS><CLONING_OPS>0</CLONING_OPS><CLONING_ID>-1</CLONING_ID><DATASTORE_ID>105</DATASTORE_ID><DATASTORE>ceph.altaria</DATASTORE><VMS><ID>60</ID></VMS><CLONES/><TEMPLATE><DEV_PREFIX><![CDATA[vd]]></DEV_PREFIX><FROM_APP><![CDATA[4fc76a938fb81d3517000003]]></FROM_APP><FROM_APP_FILE><![CDATA[0]]></FROM_APP_FILE><FROM_APP_NAME><![CDATA[ttylinux-kvm]]></FROM_APP_NAME><MD5><![CDATA[04c7d00e88fa66d9aaa34d9cf8ad6aaa]]></MD5><QUATTOR><![CDATA[1]]></QUATTOR></TEMPLATE></IMAGE></IMAGE_POOL>
```
Comment (jrha) [inline aii-opennebula/src/test/perl/rpcdata.pm]: Eugh, is there no nicer way to write this?

**Comment by jrha** [comment]
This looks mostly okay, it seems to fix a lot of things which are obviously broken in HEAD, which is good. This makes me want to merge it, but it needs more review first, which leaves me conflicted as I don't want to release code we know to be broken in 14.12.

File: aii-opennebula/src/test/perl/rpcdata.pm (hunk 2 above)
Comment (stdweird) [inline aii-opennebula/src/test/perl/rpcdata.pm]: this data is a dump from an actual run, not created by hand. it's certainly not meant to be reviewed :smile:

Comment (jrha) [inline aii-opennebula/src/test/perl/rpcdata.pm]: But my eyes, they bleed :sob:

File: aii-opennebula/src/main/perl/opennebula.pm (hunk 1 above)
Comment (alvarosimon) [inline aii-opennebula/src/main/perl/opennebula.pm]: @jrha virtual network address range acronym, yes I will include a comment to clarify this...

File: aii-opennebula/src/test/perl/rpcdata.pm (hunk 2 above)
Comment (alvarosimon) [inline aii-opennebula/src/test/perl/rpcdata.pm]: You are right, this xml crap is awful :smile: but it's the only way to mock the rpc endpoint

**Comment by piojo** [comment]
@jrha, this module is not part of the releases. It's not listed in the top-level POM. OTOH, it definitely needs a quick review...

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 3]
```diff
@@ -64,18 +66,23 @@ sub make_one
...
-    my $tpl = Template->new(INCLUDE_PATH => TEMPLATEPATH);
-    if (! $tpl->process($tt_rel, $tree, \$res)) {
-        $main::this_app->error("TT processing of $tt_rel failed: ", $tpl->error());
+    my $tpl = CAF::TextRender->new(
+        $tt_name,
+        $tree,
+        relpath => 'aii-opennebula',
+        log => $self,
+        );
+    if (!$tpl) {
```
Comment (piojo) [inline aii-opennebula/src/main/perl/opennebula.pm]: I just need a confirmation here. I assume `!$tpl` means new above returns an object, only that when stringified it becomes `""`, right?

Otherwise, the `$tpl->{fail}` below will be an attempt to dereference an undefined value, and crash.

Comment (piojo) [inline aii-opennebula/src/main/perl/opennebula.pm]: Also, can you point out to the test that exercises this error path?

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 4]
```diff
@@ -170,48 +177,92 @@ sub new
...
-            my $newimage = $one->create_image($imagedata->{image}, $imagedata->{datastore});
-            if ($newimage) {
-                $main::this_app->info("Created new VM image ID: ", $newimage->id);
-                push(@nimages, $imagename);
-            } else {
-                $main::this_app->error("VM image: $imagename is not available");
-            }
-    	}
+        $self->remove_vm_images($one, $forcecreateimage, $imagename, \@rimages);
+        # And create the new image with the image data
```
Comment (piojo) [inline aii-opennebula/src/main/perl/opennebula.pm]: Now that the code is obvious, this comment is pointless. Remove it. :smile:

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 5]
```diff
@@ -170,48 +177,92 @@ sub new
...
+        }
+    }
+}
+
+# Create new VM images
+# Returns new images array
+sub create_vm_images
+{
+    my ($self, $one, $imagename, $imagedata, $remove, $ref_nimages) = @_;
+    my $newimage;
```
Comment (piojo) [inline aii-opennebula/src/main/perl/opennebula.pm]: Empty line after `@_`;

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 6]
```diff
@@ -170,48 +177,92 @@ sub new
...
+            $main::this_app->info("Created new VM image ID: ", $newimage->id);
+            push(@{$ref_nimages}, $imagename);
+        } else {
+            $main::this_app->error("VM image: $imagename is not available");
+        }
+    }
+}
+
+# Removes current VM images
+# Returns removed images array
```
Comment (piojo) [inline aii-opennebula/src/main/perl/opennebula.pm]: I don't see any return statement here? Either the comment is misleading or we miss something.

Comment (alvarosimon) [inline aii-opennebula/src/main/perl/opennebula.pm]: @piojo you are right, the comment is outdated, now create_image and remove_image functions do not return any value.

File: aii-opennebula/src/main/perl/opennebula.pm (hunk 3 above)
Comment (alvarosimon) [inline aii-opennebula/src/main/perl/opennebula.pm]: @piojo yes, we use the same code to process the component templates

**Comment by stdweird** [comment]
@jrha i just reread the PR, it's ok for me to merge in.
