### PR TITLE
aii-opennebula: configure fix

### LINKED ISSUE #199: AII-Opennebula: hook behaviour of --configure
Right now by default --configure removes and recreates the image if it exists. This should not be done with --configure but only with --remove.

### LINKED ISSUE #204: aii-opennebula: http rpc endpoint is hardcoded
RPC url http is hardcoded from aii-opennebula code and it is not able to use https endpoints:

>  url      => "http://$host:$port/RPC2",

change aii configuration to include an url endpoint, as example:

> [rpc]
> password=...
> url=https://hostname:2634

### LINKED ISSUE #208: aii-opennebula: add some error msgs to opennebula_vmtemplate_vnet type checks
something like this 

```
--- a/cfg/standard/quattor/aii/opennebula/schema.pan
+++ b/cfg/standard/quattor/aii/opennebula/schema.pan
@@ -55,6 +55,7 @@ type opennebula_vmtemplate_vnet = string{} with {
     # check if all entries in the map have a network interface
     foreach (k;v;SELF) {
         if (! exists("/system/network/interfaces/"+k)) {
+            error(format("entry %s in the vnet map has no network interface", k)) ;
             return(false);
         };
     };
@@ -65,6 +66,7 @@ type opennebula_vmtemplate_vnet = string{} with {
              (! match('^(Bridge|OVSBridge)$', v['type'])) # these special types are OK 
              )
             ) {
+            error(format("interface %s has no entry in the vnet map", k)) ;
             return(false);
         };
     };
```

### PR DESCRIPTION
**Pull request by alvarosimon**
* Fix #199 : hook behaviour of --configure 
 * Fix #204 : http rpc endpoint is hardcoded
 * Fix #208 : add some error msgs to opennebula_vmtemplate_vnet type checks

`--configure` does not remove any image or template, only `--remove` does

### CODE REVIEW

**Comment by alvarosimon** [comment]
@kwaegema this PR solves the remove issue, please take a look. It was tested in altaria.

**Comment by ned21** [comment]
@alvarosimon - d41027e seems to do more than just more than removing hardcoded rpc. Can you please amend the commit log to explain all the changes? (or split the commit into separate ones for refactoring/functional changes if the other changes are just clean up). Same for bea31da: it appears to touch more than just the logging calls.

It's best practice too if a unit test fix up (acb88b6) is squashed into the commit that broke the build so that we don't have individual commits that are not atomic (e.g. if we need to revert 1 commit, it's not obvious that another commit may also need to be reverted). 

The commit log message for a8acfac is so brief that it does not make much sense to me but maybe that's because I am not familiar with opennebula so I'll let @kwaegema comment on whether a more expansive documentation of the change is required.

**Comment by alvarosimon** [comment]
@ned21 you are right,  I did some extra changes and the commit logs are not clear enough for the reviewer, sorry for that, I will update the PR and log commits asap

**Comment by alvarosimon** [comment]
@ned21 I think that now is a bit more clear, sorry again.
This reminds me of something... :smile: http://xkcd.com/1296/

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 1]
```diff
@@ -62,18 +62,22 @@ sub make_one
...
     };
-    my $port = $config->{$rpc}->{port} || 2633;
-    my $host = $config->{$rpc}->{host} || "localhost";
+    my $port = $config->{$rpc}->{port};
+    my $host = $config->{$rpc}->{host};
+    my $url = $config->{$rpc}->{url} || "http://localhost:2633";
     my $user = $config->{$rpc}->{user} || "oneadmin";
     my $password = $config->{$rpc}->{password};
 
+    $url = "http://$host:2633" if ($host);
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: this overwrites the url set by `$config->{$rpc}->{url}` if only $host is set?
One should probably specify `url NAND (host OR port)`  since you have defaults, otherwise this can be ambiguous, (and I would throw an error in that case..) Then, if the `url` is set, take that one, if not keep old behavior to keep backwards compatibility ?

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 2]
```diff
@@ -62,18 +62,22 @@ sub make_one
...
+
     if (! $password ) {
         $main::this_app->error("No password set in configfile $filename. Section [$rpc]");
         return;
     }
-    
+
     my $one = Net::OpenNebula->new(
-        url      => "http://$host:$port/RPC2",
+        url      => "$url/RPC2",
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: you still have `host` and `port` variables, but port is `never` used

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 3]
```diff
@@ -29,10 +29,10 @@ use constant MINIMAL_ONE_VERSION => version->new("4.8.0");
 use constant BOOT_V4 => [qw(network hd)];
 use constant BOOT_V5 => [qw(nic0 disk0)];
 
-# a config file in .ini style with minmal 
+# a config file in .ini style with minmal
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: minimal? minimal what? :smile:

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 4]
```diff
@@ -294,36 +301,35 @@ sub remove_and_create_vm_images
...
-    if (!$remove) {
-        if ($self->is_one_resource_available($one, "image", $imagename)) {
-            $main::this_app->error("Image: $imagename is already used and AII hook: image is not set. ",
-                                    "Please remove this image first.");
-        } else {
+    if ($self->is_one_resource_available($one, "image", $imagename)) {
+        $main::this_app->warn("Image: $imagename is already available from OpenNebula. ",
+                              "Please remove this image first if you want to generate a new one from scratch.");
+        return;
+    } else {
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: not needed since you do a `return`

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 5]
```diff
@@ -472,20 +479,20 @@ sub stop_and_remove_one_vms
...
-    
+
     # Check if the vm template already exists
     my @existtmpls = $one->get_templates(qr{^$fqdn$});
 
     foreach my $t (@existtmpls) {
         if ($t->{extended_data}->{TEMPLATE}->[0]->{QUATTOR}->[0]) {
-            if ($createvmtemplate) {
+            if ($remove) {
                 # force to remove and create the template again
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: this only removes it, no?

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 6]
```diff
@@ -496,7 +503,7 @@ sub remove_and_create_vm_template
             $main::this_app->info("No QUATTOR flag found for VM template: ",$t->name);
         }
     }
-    
+
     if ($createvmtemplate && !$remove) {
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: I don't understand how this works, but probably  I don't completely get what the `$remove` flag means

Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: OK, I already get it :smile:

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 7]
```diff
@@ -472,20 +479,20 @@ sub stop_and_remove_one_vms
 sub remove_and_create_vm_template
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: The name of the sub is confusing right now. It is more a remove_or_create_vm_template, depending on the $remove flag. I would make it more clear that what this sub does (removing or creating) is depending on the context it is called (configure or remove)

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 8]
```diff
@@ -267,25 +271,28 @@ sub get_resource_instance
 
 sub remove_and_create_vm_images
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: Same remakr about sub name and some doc context  maybe

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 9]
```diff
@@ -705,20 +708,20 @@ sub remove
...
 
+    my $vmtemplatetxt = $self->get_vmtemplate($config, $oneversion);
+    if ($vmtemplatetxt) {
+        $self->remove_and_create_vm_template($one, $fqdn, 1, $vmtemplatetxt, undef, $rmvmtemplate);
+    }
+
     my %images = $self->get_images($config);
     if (%images) {
-        $self->remove_and_create_vm_images($one, 1, \%images, undef, $rmimage);
+        $self->remove_and_create_vm_images($one, undef, \%images, undef, $rmimage);
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: Is there a reason this is called when `$rmimage` is false?

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 10]
```diff
@@ -705,20 +708,20 @@ sub remove
         $self->stop_and_remove_one_vms($one,$fqdn);
     }
 
+    my $vmtemplatetxt = $self->get_vmtemplate($config, $oneversion);
+    if ($vmtemplatetxt) {
+        $self->remove_and_create_vm_template($one, $fqdn, 1, $vmtemplatetxt, undef, $rmvmtemplate);
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: Should this be called when  $rmvmtemplate is false. The current behavior now is to update the template then when it is false (which I guess is not needed in a remove context)

**Comment by kwaegema** [comment]
@alvarosimon I added some remarks.

Maybe it is also nice to describe somewhere (in the pod?) how the opennebula parts (vm, image, template,..) map to the typical aii parts `remove` , `configure`, `install` . 
Something like 
remove: stop vm, remove vm/image/template/.. 
configure: creating / updating .. which resources (again) ? 
install: only instantiate machine created by resources of configure ?

Unless that is already described somewhere I don't know of :smile:

File: aii-opennebula/src/main/perl/opennebula.pm (hunk 1 above)
Comment (alvarosimon) [inline aii-opennebula/src/main/perl/opennebula.pm]: @kwaegema ah ok I will change this, in any case the ambiguity disappears due to the opennebula metaconfig aii setup that only allows urls setup: https://github.com/quattor/configuration-modules-core/pull/788

**Comment by alvarosimon** [comment]
@kwaegema thanks for the review! I have addressed your remarks, but if something is missing or it is not clear please let me know :smile:

File: aii-opennebula/src/main/perl/opennebula.pod [hunk 11]
```diff
@@ -96,8 +99,6 @@ All these paths are relative to /system/aii/hooks/remove
 
 Stop running VM
 
-=over 4
```
Comment (wdpypere) [inline aii-opennebula/src/main/perl/opennebula.pod]: if you remove the ```=over``` here, you'll have to remove one of the  ```=back``` a bit further as well.

Comment (wdpypere) [inline aii-opennebula/src/main/perl/opennebula.pod]: hmm, don't we validate pods in AII tests?

```code```
[wdpypere@scyther ~]$ podchecker opennebula.pod 
*** ERROR: =back without =over at line 112 in file opennebula.pod
opennebula.pod has 1 pod syntax error.
```

Comment (alvarosimon) [inline aii-opennebula/src/main/perl/opennebula.pod]: Ups.. thanks I forgot that, now the syntax is ok

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 12]
```diff
@@ -269,7 +271,7 @@ sub get_resource_instance
     return;
 }
 
-sub remove_and_create_vm_images
+sub remove_or_create_vm_images
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: add docstring

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 13]
```diff
@@ -476,7 +478,7 @@ sub stop_and_remove_one_vms
 
 # Creates and removes VM templates
 # $createvmtemplate hook forces to remove/create
-sub remove_and_create_vm_template
+sub remove_or_create_vm_template
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]: update docstring

File: aii-opennebula/src/main/perl/opennebula.pod (hunk 11 above)
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pod]: It is included with the components in configuration-modules-core, but not here it seems. @alvarosimon you can add the file pod-syntax.t to the test dir with contents 

```
use Test::More;
use Test::Pod;

my @dirs = qw(target/lib/perl target/doc/pod);
all_pod_files_ok(all_pod_files(@dirs));
```

Comment (alvarosimon) [inline aii-opennebula/src/main/perl/opennebula.pod]: Ah yes.. pod-syntax.t is missing... :disappointed: I will include that thanks!

**Comment by alvarosimon** [comment]
@wdpypere @kwaegema remarks addressed

**Comment by kwaegema** [comment]
I'm still thinking the $url override by a $host is weird, but if metaconfig enforces this (and everyone should use metaconfig :smile: ), I guess it doesn't matter. besides that, LGTM!

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 14]
```diff
@@ -63,17 +65,21 @@ sub make_one
         $main::this_app->info ("Detected configfile RPC section: [$rpc]");
     };
     my $port = $config->{$rpc}->{port} || 2633;
-    my $host = $config->{$rpc}->{host} || "localhost";
+    my $host = $config->{$rpc}->{host};
+    my $url = $config->{$rpc}->{url} || "http://localhost:2633/RPC2";
```
Comment (stdweird) [inline aii-opennebula/src/main/perl/opennebula.pm]: the defaults (inlc port and user) should be readonlys, like `Readonly my ONE_DEFAULT_URL => 'http://localhost:2633/RPC2';`

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 15]
```diff
@@ -63,17 +65,21 @@ sub make_one
...
     my $user = $config->{$rpc}->{user} || "oneadmin";
     my $password = $config->{$rpc}->{password};
 
+    # Keep backwards compatibility
+    $url = "http://$host:$port/RPC2" if ($host);
```
Comment (stdweird) [inline aii-opennebula/src/main/perl/opennebula.pm]: add a log warning here that the url is redefined

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 16]
```diff
@@ -63,17 +65,21 @@ sub make_one
...
+
     if (! $password ) {
         $main::this_app->error("No password set in configfile $filename. Section [$rpc]");
         return;
     }
-    
+
     my $one = Net::OpenNebula->new(
-        url      => "http://$host:$port/RPC2",
+        url      => "$url",
```
Comment (stdweird) [inline aii-opennebula/src/main/perl/opennebula.pm]: no quotes around `$url`?

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 17]
```diff
@@ -462,30 +472,32 @@ sub stop_and_remove_one_vms
             $main::this_app->info("Running VM will be removed: ",$t->name);
             $t->delete();
         } else {
-            $main::this_app->info("No QUATTOR flag found for Running VM: ",$t->name);
+            $main::this_app->info("No QUATTOR flag found for Running VM: ", $t->name);
```
Comment (stdweird) [inline aii-opennebula/src/main/perl/opennebula.pm]: please add in the message that you stop processing and other `@runingvms` here?
but is the return really necessary?

File: aii-opennebula/src/main/perl/opennebula.pod (hunk 11 above)
Comment (stdweird) [inline aii-opennebula/src/main/perl/opennebula.pod]: see also #206

File: aii-opennebula/src/main/perl/opennebula.pm (hunk 17 above)
Comment (alvarosimon) [inline aii-opennebula/src/main/perl/opennebula.pm]: No  `return` is not necessary in this case, I will remove that

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 18]
```diff
@@ -23,6 +23,7 @@ use constant DOMAINNAME => "/system/network/domainname";
 use constant MAXITER => 20;
 use constant TIMEOUT => 30;
 use constant MINIMAL_ONE_VERSION => version->new("4.8.0");
+use constant ONE_DEFAULT_URL => 'http://localhost:2633/RPC2';
```
Comment (kwaegema) [inline aii-opennebula/src/main/perl/opennebula.pm]:
```
use Readonly;
Readonly my ONE_DEFAULT_URL => 'http://localhost:2633/RPC2';
```
like https://github.com/quattor/configuration-modules-core/blob/master/ncm-ceph/src/main/perl/Ceph/crushmap.pm#L42

Comment (alvarosimon) [inline aii-opennebula/src/main/perl/opennebula.pm]: @stdweird should we switch to `Readonly` the rest of the constant values as well? `MINIMAL_ONE_VERSION`, `TIMEOUT`...

Comment (stdweird) [inline aii-opennebula/src/main/perl/opennebula.pm]: up to you, but we should not mix constant and Readonly, that's just confusing

**Comment by alvarosimon** [comment]
@stdweird remarks addressed

File: aii-opennebula/src/main/perl/opennebula.pm [hunk 19]
```diff
@@ -347,7 +362,7 @@ sub is_timeout
     my ($self, $one, $resource, $name) = @_;
     eval {
         local $SIG{ALRM} = sub { die "alarm\n" };
-        alarm TIMEOUT;
+        alarm $TIMEOUT;
```
Comment (piojo) [inline aii-opennebula/src/main/perl/opennebula.pm]: Doesn't `$SIG{ALRM}` cause a `die`?

Comment (alvarosimon) [inline aii-opennebula/src/main/perl/opennebula.pm]: @piojo from http://perldoc.perl.org/functions/alarm.html it seems that you should use `eval/die` to be sure that the timeout will work (but I'm not a perl guru, I'm not sure why..)

File: aii-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan [hunk 20]
```diff
@@ -55,6 +55,7 @@ type opennebula_vmtemplate_vnet = string{} with {
     # check if all entries in the map have a network interface
     foreach (k;v;SELF) {
         if (! exists("/system/network/interfaces/"+k)) {
+            error(format("entry: %s in the vnet map is not available from /system/network/interfaces tree", k));
```
Comment (alvarosimon) [inline aii-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan]: @piojo ah ok, I have changed that, thanks for the tip

**Comment by jrha** [comment]
LGTM. @piojo are you happy with this now?
