### PR TITLE
ks: add useexisting when using el7 with md

### LINKED ISSUE #102: software raids installed on boot,swap and root partitions with kickstart not working under el7
raid .... --noformat seems not to assemble nor mount the used devices. This is only done when using  --useexisting

How I got it to work manually:
```
raid /boot --device=md1 --useexisting
raid swap --device=md3 --useexisting
raid / --device=md2 --fstype=ext4 --fsoptions='defaults' --useexisting
```
and in %pre section:
```
mdadm --stop /dev/md2
mdadm --stop /dev/md1
mdadm --stop /dev/md3
```

### PR DESCRIPTION
**Pull request by kwaegema**
fixes #102 
depends on https://github.com/quattor/ncm-lib-blockdevices/pull/64

On EL7 Anaconda, mdadm should stop the devices at the end of the pre section, 
and should add the --useexisting flag on the already created MD devices.

### CODE REVIEW

File: aii-ks/src/main/perl/ks.pm [hunk 1]
```diff
@@ -814,6 +817,13 @@ EOF
     ksuserhooks ($config, PREENDHOOK);
 
     my $end = $config->getElement(END_SCRIPT_FIELD)->getValue();
+    my $kstree = $config->getElement(KS)->getTree;
+    my $version = get_anaconda_version($kstree);
+
+    # mdadm devices should be stopped at the end of the pre-ks phase on EL7
+    if ($version >= ANACONDA_VERSION_EL_7_0) {
+        print "mdadm --stop --scan";
```
Comment (stdweird) [inline aii-ks/src/main/perl/ks.pm]: no newline to print?

**Comment by jrha** [comment]
@kwaegema this looks like it needs rebasing

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
Tests fails due to #178

**Comment by jrha** [comment]
rebase and retest?

**Comment by jrha** [comment]
LGTM

**Comment by stdweird** [comment]
LGTM 
(we've been using this for a while)
